USE [master]
GO
/****** Object:  Database [Project_BGT]    Script Date: 07-04-2023 19:31:00 ******/
CREATE DATABASE [Project_BGT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Project_BGT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Project_BGT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Project_BGT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Project_BGT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Project_BGT] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Project_BGT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Project_BGT] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Project_BGT] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Project_BGT] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Project_BGT] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Project_BGT] SET ARITHABORT OFF 
GO
ALTER DATABASE [Project_BGT] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Project_BGT] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Project_BGT] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Project_BGT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Project_BGT] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Project_BGT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Project_BGT] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Project_BGT] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Project_BGT] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Project_BGT] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Project_BGT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Project_BGT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Project_BGT] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Project_BGT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Project_BGT] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Project_BGT] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Project_BGT] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Project_BGT] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Project_BGT] SET  MULTI_USER 
GO
ALTER DATABASE [Project_BGT] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Project_BGT] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Project_BGT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Project_BGT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Project_BGT] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Project_BGT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Project_BGT] SET QUERY_STORE = ON
GO
ALTER DATABASE [Project_BGT] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Project_BGT]
GO
/****** Object:  Schema [Project_BGT]    Script Date: 07-04-2023 19:31:00 ******/
CREATE SCHEMA [Project_BGT]
GO
/****** Object:  Table [Project_BGT].[Innings_Records]    Script Date: 07-04-2023 19:31:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Project_BGT].[Innings_Records](
	[Test Series Year] [varchar](50) NOT NULL,
	[Test Number] [int] NOT NULL,
	[Innings] [int] NOT NULL,
	[Highest Scorer] [varchar](50) NOT NULL,
	[Runs by highest scorer] [int] NOT NULL,
	[best bowler] [varchar](50) NOT NULL,
	[wickets by best bowler] [int] NOT NULL,
	[Runs per Innings] [int] NOT NULL,
	[Wickets Fallen] [int] NOT NULL,
 CONSTRAINT [PK_Innings_Records] PRIMARY KEY CLUSTERED 
(
	[Test Series Year] ASC,
	[Test Number] ASC,
	[Innings] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Project_BGT].[Match_Location]    Script Date: 07-04-2023 19:31:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Project_BGT].[Match_Location](
	[Venue] [varchar](50) NOT NULL,
	[Host] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Match_Location] PRIMARY KEY CLUSTERED 
(
	[Venue] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Project_BGT].[Match_Narration]    Script Date: 07-04-2023 19:31:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Project_BGT].[Match_Narration](
	[Test Series Year] [varchar](50) NOT NULL,
	[Test Number] [int] NOT NULL,
	[Venue] [varchar](50) NOT NULL,
	[Winner] [varchar](50) NOT NULL,
	[Win Margin Descriptive] [varchar](50) NOT NULL,
	[Man of the Match] [varchar](50) NOT NULL,
	[Ind captain] [varchar](50) NOT NULL,
	[Aus captain] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Match_Narration] PRIMARY KEY CLUSTERED 
(
	[Test Series Year] ASC,
	[Test Number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Project_BGT].[Streak_Achievement]    Script Date: 07-04-2023 19:31:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Project_BGT].[Streak_Achievement](
	[Test Series Year] [varchar](50) NOT NULL,
	[Man of the Series] [varchar](50) NOT NULL,
	[Series Victory] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Streak_Achievement] PRIMARY KEY CLUSTERED 
(
	[Test Series Year] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [Project_BGT].[Top_Scorer]    Script Date: 07-04-2023 19:31:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Project_BGT].[Top_Scorer](
	[Highest Scorer] [varchar](50) NOT NULL,
	[Team] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Top_Scorer] PRIMARY KEY CLUSTERED 
(
	[Highest Scorer] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Project_BGT].[Innings_Records]  WITH CHECK ADD  CONSTRAINT [FK_Innings_Records_Match_Narration] FOREIGN KEY([Test Series Year], [Test Number])
REFERENCES [Project_BGT].[Match_Narration] ([Test Series Year], [Test Number])
GO
ALTER TABLE [Project_BGT].[Innings_Records] CHECK CONSTRAINT [FK_Innings_Records_Match_Narration]
GO
ALTER TABLE [Project_BGT].[Innings_Records]  WITH CHECK ADD  CONSTRAINT [FK_Innings_Records_Top_Scorer] FOREIGN KEY([Highest Scorer])
REFERENCES [Project_BGT].[Top_Scorer] ([Highest Scorer])
GO
ALTER TABLE [Project_BGT].[Innings_Records] CHECK CONSTRAINT [FK_Innings_Records_Top_Scorer]
GO
ALTER TABLE [Project_BGT].[Match_Narration]  WITH CHECK ADD  CONSTRAINT [FK_Match_Narration_Match_Location] FOREIGN KEY([Venue])
REFERENCES [Project_BGT].[Match_Location] ([Venue])
GO
ALTER TABLE [Project_BGT].[Match_Narration] CHECK CONSTRAINT [FK_Match_Narration_Match_Location]
GO
ALTER TABLE [Project_BGT].[Match_Narration]  WITH CHECK ADD  CONSTRAINT [FK_Match_Narration_Streak_Achievement] FOREIGN KEY([Test Series Year])
REFERENCES [Project_BGT].[Streak_Achievement] ([Test Series Year])
GO
ALTER TABLE [Project_BGT].[Match_Narration] CHECK CONSTRAINT [FK_Match_Narration_Streak_Achievement]
GO
USE [master]
GO
ALTER DATABASE [Project_BGT] SET  READ_WRITE 
GO
